In [5]:
import numpy as np

In [7]:
np.random.randint(100)

40

# multiplication of array

In [6]:
e1= np.random.random((3,3))

In [7]:
e1.dtype

dtype('float64')

In [8]:
e1=e1*100

In [9]:
e1=e1.astype("int") # changed array to int type
e1

array([[36, 92, 38],
       [17, 27, 23],
       [78,  6, 10]])

In [10]:
e1.dtype

dtype('int64')

In [16]:
e2 = np.random.random((3,3))
e2=e2*100
e2=e2.astype("int")
e2

array([[64, 39, 77],
       [82,  7, 91],
       [23, 85, 53]])

In [36]:
e1.shape()

(3, 3)
(3, 3)


In [37]:
e1@e2 #read about this decorator

array([[ 7913,  3090,  9478],
       [10879,  7733, 14135],
       [10143,  6388, 12684]])

In [40]:
e1.dot(e2) #read about dot function

array([[ 7913,  3090,  9478],
       [10879,  7733, 14135],
       [10143,  6388, 12684]])

In [39]:
g= np.linspace(1,10,3)

In [41]:
g

array([ 1. ,  5.5, 10. ])

In [11]:
d=np.random.random((4,4))
d=d*100
d=d.astype("int")

In [15]:
d

array([[12, 81, 82,  5],
       [32,  8, 69, 79],
       [29, 24, 95, 67],
       [53, 33, 81, 28]])

In [120]:
print(d[:1])

[[12 81 82  5]]


In [114]:
d2 = np.zeros((4,1))

In [121]:
for i, x in enumerate(d[:]):
    print(i,x)
    d2[i]= x[:1]
    print(x[:1])    
print(d2)
            

0 [12 81 82  5]
[12]
1 [32  8 69 79]
[32]
2 [29 24 95 67]
[29]
3 [53 33 81 28]
[53]
[[12.]
 [32.]
 [29.]
 [53.]]


In [33]:
temp = d[:,:1]

In [34]:
temp

array([[12],
       [32],
       [29],
       [53]])

In [100]:
d

array([[12, 81, 82,  5],
       [32,  8, 69, 79],
       [29, 24, 95, 67],
       [53, 33, 81, 28]])

In [103]:
d[[0,2],[2,3]]

array([82, 67])

In [104]:
d2=d[[[0,1,2,3],[0,1,2,3]],[[0,1,2,3],[3,2,1,0]]]

In [105]:
d2

array([[12,  8, 95, 28],
       [ 5, 69, 24, 53]])

In [106]:
d2.T

array([[12,  5],
       [ 8, 69],
       [95, 24],
       [28, 53]])

In [117]:
new=d2.reshape()
new

array([43, 12, 13, 80, 12, 30,  1,  4])

In [126]:
d[[i for i in range(d.shape[0])], [i for i in range(d.shape[1])]]

array([12,  8, 95, 28])

In [ ]:
d[[i for i in range(d.shape[0])], [i for in range(d.shape[])]]

In [48]:
x= np.random.random((3,3))

In [49]:
x=x*100
x=x.astype("int")
x

array([[47, 65, 85],
       [64, 75, 66],
       [15, 36, 63]])

In [50]:
cond = x>50

In [51]:
cond

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [52]:
temp=x[cond]

In [53]:
temp

array([65, 85, 64, 75, 66, 63])

In [54]:
x[x > 50] #same as above

array([65, 85, 64, 75, 66, 63])

# Given number of students n, input their name, grad_year, cgpa. Find class average 

In [135]:
n = int(input())

dtype = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
values = []
for _ in range(n):
    name = input()
    grad_year = int(input())
    cgpa = float(input())
    x=()
    x.append(name)
    x.append(grad_year)
    x.append(cgpa)2
values.append(x)    

2
Abhihsek
2022
8.9


AttributeError: 'tuple' object has no attribute 'append'

In [134]:
values

['Abhishek', 2022, 8.4, 'Jatin', 2019, 8.0, 'patel', 2022, 7.0]